name: AI Content and Medium Blog Search

on:
  schedule:
    - cron: "0 6,14,22 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

env:
  SEARCH_QUERY: "artificial intelligence"
  MEDIUM_TOPIC: "artificial intelligence"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Run AI content and Medium blog search script
        run: python .github/scripts/content_search.py
        env:
          SEARCH_QUERY: ${{ env.SEARCH_QUERY }}
          MEDIUM_TOPIC: ${{ env.MEDIUM_TOPIC }}
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update AI content and Medium blogs in README" && git push)