name: AI Content Update

on:
  workflow_dispatch:
    inputs:
      search_topic:
        description: 'Topic to search (e.g., artificial intelligence, machine learning)'
        required: true
        default: 'artificial intelligence'
      medium_tag:
        description: 'Medium tag for additional articles'
        required: true
        default: 'machine-learning'

  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Fetch and Update README
      run: python .github/scripts/ai_content_search.py ${{ github.event.inputs.search_topic }} ${{ github.event.inputs.medium_tag }}
